---
docker:
  host: "https://boot2docker:2376"
  ssl_verify_peer: false

stacks:
  - name: proxy
    units:

      - name: base
        version: 1.0.0
        dockerfile: _base/Dockerfile
        startable: false

      - name: front-lb
        version: 1.0.0
        dockerfile: front-lb/Dockerfile
        ports:
          - 8888:80
        dependant_unit_names:
          - base
          - front-proxy1
          - front-proxy2

      - name: front-proxy
        instances: 2
        version: 1.0.0
        dockerfile: front-proxy/Dockerfile
        dependant_unit_names:
          - base
          - app-lb1
          - app-lb2

      - name: app-lb
        instances: 2
        version: 1.0.0
        dockerfile: app-lb/Dockerfile
        dependant_unit_names:
          - base
          - app1
          - app2
          - app3

      - name: app
        instances: 4
        version: 1.0.0
        dockerfile: app/Dockerfile
        dependant_unit_names:
          - base
